version: "3"

services:
    server:
        build: 
            context: ./server
        ports:
            - "7171:7171"
            - "7172:7172"
            - "80:80"
            - "8080:8080"
        container_name: server
        volumes:
            - serverVolume:/otserver
    db:
        build: 
            context: ./db
        ports:
            - "3306:3306"
        container_name: db
volumes:
    serverVolume: